use std::sync::Arc;

use anyhow::{Result, anyhow};
use chrono::{SecondsFormat, Utc};

use crate::application::port::outbound::planning_task_repository_port::{
    PlanningTaskAuthorityCommit, PlanningTaskAuthorityCommitResult, PlanningTaskRepositoryPort,
};
use crate::application::port::outbound::planning_workspace_port::{
    PlanningWorkspaceLoadRecord, PlanningWorkspacePort,
};
use crate::application::service::planning::runtime::prompt::{
    PlanningPromptService, PlanningRuntimeSnapshot,
};
use crate::application::service::planning::runtime::validation::PlanningValidationService;
use crate::domain::planning::PriorityQueueService;
use crate::domain::planning::{
    DirectionCatalogDocument, PLANNING_FORMAT_VERSION, PlanningWorkspaceFiles, TaskActor,
    TaskAuthorityDocument, TaskStatus,
};

#[derive(Debug, Clone, PartialEq, Eq)]
/*
 * Promotion is scoped to one workspace and one root turn.
 * The workspace identifies which planning authority set should be rewritten; the root turn is kept in
 * the request contract so callers can tie a promotion attempt back to the turn that decided the queue
 * was idle, even though this service currently promotes strictly from repository state.
 */
pub struct PlanningProposalPromotionRequest<'a> {
    // Filesystem and repository adapters both use this value as the planning workspace boundary.
    pub workspace_directory: &'a str,
    // Preserved for auditability of queue-idle decisions made by the worker/runtime layer.
    pub root_turn_id: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
/*
 * The caller receives a fresh runtime snapshot regardless of whether a proposal was promoted.
 * That keeps worker orchestration simple: after the service returns, it can render or submit against the
 * same snapshot shape and use the boolean/title/notices only to describe whether authority changed.
 */
pub struct PlanningProposalPromotionOutcome {
    // Reloaded after the no-op check or after the commit so queue state reflects the authoritative store.
    pub runtime_snapshot: PlanningRuntimeSnapshot,
    // Operator-facing messages generated by the application service, not by adapters.
    pub notices: Vec<String>,
    // Present only for a successful promotion and copied from the proposal projection for stable wording.
    pub promoted_task_title: Option<String>,
    // Distinguishes a valid no-op from an authority rewrite.
    pub promoted: bool,
}

#[derive(Clone)]
/*
 * Application service that closes the gap between runtime queue inspection and authority mutation.
 * It reads current planning documents through ports, asks the domain queue service which proposed task is
 * promotable, validates the complete workspace before writing, and commits through the repository port
 * with an observed revision guard.
 */
pub struct PlanningProposalPromotionService {
    // Workspace files provide result-output content required by whole-workspace validation.
    planning_workspace_port: Arc<dyn PlanningWorkspacePort>,
    // Runtime snapshot reload is delegated to the same prompt service used by normal worker turns.
    planning_prompt_service: PlanningPromptService,
    // Promotion writes are allowed only from a workspace that is valid before the mutation.
    planning_validation_service: PlanningValidationService,
    // Domain projection decides whether a ready task already exists and which proposal ranks first.
    priority_queue_service: PriorityQueueService,
    // Repository port owns accepted authority snapshots and conflict-aware commits.
    planning_task_repository_port: Arc<dyn PlanningTaskRepositoryPort>,
}

impl PlanningProposalPromotionService {
    #[cfg(test)]
    #[allow(dead_code)]
    /*
     * Tests can construct the service without a real repository boundary.
     * Production composition uses with_task_repository so proposal promotion participates in the same
     * accepted-authority transaction model as manual planning edits.
     */
    pub fn new(
        planning_workspace_port: Arc<dyn PlanningWorkspacePort>,
        planning_prompt_service: PlanningPromptService,
        planning_validation_service: PlanningValidationService,
        priority_queue_service: PriorityQueueService,
    ) -> Self {
        Self::with_task_repository(
            planning_workspace_port,
            planning_prompt_service,
            planning_validation_service,
            priority_queue_service,
            Arc::new(crate::application::port::outbound::planning_task_repository_port::NoopPlanningTaskRepositoryPort),
        )
    }

    /*
     * Composition injects all collaboration points explicitly.
     * Keeping the repository as a port dependency lets filesystem-backed and DB-backed authority stores
     * enforce the same optimistic revision contract without changing promotion logic.
     */
    pub fn with_task_repository(
        planning_workspace_port: Arc<dyn PlanningWorkspacePort>,
        planning_prompt_service: PlanningPromptService,
        planning_validation_service: PlanningValidationService,
        priority_queue_service: PriorityQueueService,
        planning_task_repository_port: Arc<dyn PlanningTaskRepositoryPort>,
    ) -> Self {
        Self {
            planning_workspace_port,
            planning_prompt_service,
            planning_validation_service,
            priority_queue_service,
            planning_task_repository_port,
        }
    }

    /*
     * Promote exactly one proposed task when the executable queue is otherwise empty.
     * The operation is intentionally conservative: if a ready task already exists, or no proposed task is
     * promotable, it returns a current runtime snapshot without writing authority. When it does promote,
     * it rebuilds the queue projection after mutation and commits with the revision observed during load.
     */
    pub fn promote_top_proposal_to_ready_if_needed(
        &self,
        request: PlanningProposalPromotionRequest<'_>,
    ) -> Result<PlanningProposalPromotionOutcome> {
        // Workspace files are loaded first because validation needs the result-output prompt alongside DB authorities.
        let workspace_record = self
            .planning_workspace_port
            .load_planning_workspace_files(request.workspace_directory)?;
        // Loading through the helper validates the complete accepted state and returns the revision guard.
        let (directions, mut task_authority, observed_planning_revision) =
            self.load_valid_workspace_documents(request.workspace_directory, &workspace_record)?;
        // The domain queue projection defines both "already has executable work" and "top proposal".
        let queue_projection = self
            .priority_queue_service
            .build_projection(&directions, &task_authority)?;
        // A ready next task means worker orchestration already has executable work, so promotion would reorder intent.
        if queue_projection.next_task.is_some() || queue_projection.proposed_tasks.is_empty() {
            return Ok(PlanningProposalPromotionOutcome {
                runtime_snapshot: self
                    .planning_prompt_service
                    .load_runtime_snapshot(request.workspace_directory)?,
                notices: Vec::new(),
                promoted_task_title: None,
                promoted: false,
            });
        }

        // The projection is consumed so the selected proposal cannot drift from the ordering just evaluated.
        let top_proposal = queue_projection
            .proposed_tasks
            .into_iter()
            .next()
            .ok_or_else(|| anyhow!("proposal promotion requested without a promotable proposal"))?;
        // Authority is rewritten by task id, not title, because titles are presentation text.
        let promoted_task = task_authority
            .tasks
            .iter_mut()
            .find(|task| task.id.trim() == top_proposal.task_id.trim())
            .ok_or_else(|| {
                anyhow!(
                    "top promotable proposal {} was not found in task authority",
                    top_proposal.task_id
                )
            })?;

        // The mutation is deliberately minimal: only status and system audit metadata change.
        promoted_task.status = TaskStatus::Ready;
        promoted_task.last_updated_by = TaskActor::System;
        promoted_task.updated_at = Utc::now().to_rfc3339_opts(SecondsFormat::Secs, true);

        // Commit receives the post-mutation projection so repository adapters can persist denormalized queue state.
        let next_queue_projection = self
            .priority_queue_service
            .build_projection(&directions, &task_authority)?;
        // Proposal promotion is a system-owned authority rewrite for one queued
        // proposal, guarded by the observed revision from the loaded snapshot.
        match self
            .planning_task_repository_port
            .commit_task_authority_snapshot(
                request.workspace_directory,
                PlanningTaskAuthorityCommit {
                    // Optimistic locking prevents a stale worker-side promotion from overwriting operator edits.
                    observed_planning_revision: Some(observed_planning_revision),
                    task_authority: &task_authority,
                    queue_projection: &next_queue_projection,
                },
            )? {
            // Successful commits leave the refreshed runtime snapshot as the next source of truth.
            PlanningTaskAuthorityCommitResult::Committed { .. } => {}
            PlanningTaskAuthorityCommitResult::Conflict {
                observed_planning_revision,
                current_planning_revision,
            } => {
                anyhow::bail!(
                    "planning db changed while promoting proposal (observed revision {observed_planning_revision}, current revision {current_planning_revision}); reload and retry"
                );
            }
        }

        // Reload after commit so downstream worker policy sees the promoted task as normal ready work.
        let runtime_snapshot = self
            .planning_prompt_service
            .load_runtime_snapshot(request.workspace_directory)?;

        // Notices use the projection title because it already represents the task as the queue presented it.
        let promoted_task_title = top_proposal.task_title.trim().to_string();
        let mut notices = Vec::new();
        notices.push(format!(
            "host promoted top follow-up proposal into the executable queue: {}",
            promoted_task_title
        ));

        Ok(PlanningProposalPromotionOutcome {
            runtime_snapshot,
            notices,
            promoted_task_title: Some(promoted_task_title),
            promoted: true,
        })
    }

    /*
     * Build the validated authority pair used for promotion.
     * The repository snapshots are the accepted planning authority, while result-output still comes from
     * the workspace port; validation combines both so promotion never writes from a partially invalid
     * workspace. The returned revision is the exact task-authority version later used for conflict checks.
     */
    fn load_valid_workspace_documents(
        &self,
        workspace_dir: &str,
        workspace_record: &PlanningWorkspaceLoadRecord,
    ) -> Result<(DirectionCatalogDocument, TaskAuthorityDocument, i64)> {
        // Task authority is the only document this service mutates, so its revision becomes the write guard.
        let snapshot = self
            .planning_task_repository_port
            .load_task_authority_snapshot(workspace_dir)?
            .ok_or_else(|| anyhow!("planning task authority is unavailable"))?;
        // Direction authority is read to validate task direction links and to rebuild queue projection.
        let directions_snapshot = self
            .planning_task_repository_port
            .load_direction_authority_snapshot(workspace_dir)?
            .ok_or_else(|| anyhow!("planning direction authority is unavailable"))?;
        // Validation expects the task document in the same JSON form it would read from a workspace file.
        let task_authority_json = serde_json::to_string(&snapshot.task_authority)?;
        let validation_result =
            self.planning_validation_service
                .validate_workspace_files(workspace_record_to_files(
                    workspace_record,
                    &directions_snapshot.directions,
                    &task_authority_json,
                )?);
        // Promotion is a queue convenience, not a repair tool; invalid planning state must be fixed first.
        if !validation_result.is_valid() {
            let first_error = validation_result
                .report
                .errors()
                .first()
                .map(|issue| issue.message.clone())
                .unwrap_or_else(|| "planning validation failed".to_string());
            return Err(anyhow!(
                "cannot promote proposal from an invalid planning workspace: {first_error}"
            ));
        }

        // Use the parsed documents returned by validation so downstream projection sees normalized state.
        let directions = validation_result
            .directions
            .ok_or_else(|| anyhow!("validated planning workspace did not include directions"))?;
        let task_authority = validation_result.task_authority.ok_or_else(|| {
            anyhow!("validated planning workspace did not include task-authority")
        })?;
        // The queue projection and repository commit contract are versioned with the planning document schema.
        if task_authority.version != PLANNING_FORMAT_VERSION {
            return Err(anyhow!(
                "unsupported task-authority version {}; expected {}",
                task_authority.version,
                PLANNING_FORMAT_VERSION
            ));
        }

        Ok((directions, task_authority, snapshot.planning_revision))
    }
}

/*
 * Adapter from the workspace-port load shape into the validation domain input.
 * Direction and task authority are supplied from the repository snapshots, while result-output markdown
 * comes from the workspace record because it is still a supporting file rather than DB authority.
 */
fn workspace_record_to_files<'a>(
    workspace_record: &'a PlanningWorkspaceLoadRecord,
    directions: &'a DirectionCatalogDocument,
    task_authority_json: &'a str,
) -> Result<PlanningWorkspaceFiles<'a>> {
    Ok(PlanningWorkspaceFiles {
        directions,
        task_authority_json,
        // Missing result-output blocks promotion because validation cannot prove the runtime prompt contract.
        result_output_markdown: workspace_record
            .result_output_markdown
            .as_deref()
            .ok_or_else(|| anyhow!("planning workspace is missing result-output.md"))?,
    })
}
